### ISSUE TITLE
How to get the output as your project page

### ISSUE THREAD

**Issue by Dandelionym** [facebookresearch/MCC#10]
Excellent work! One question I want to ask:

I got the shape by `demo.py` like this:
![image](https://user-images.githubusercontent.com/62579469/218245547-196d90a2-585c-481d-913a-be0a18a3adce.png)

But your paper gives the result like this:
![image](https://user-images.githubusercontent.com/62579469/218245591-1627b096-e205-4677-93f4-ff92f1d40bc7.png)

#### Question: How to get the second one?

**Comment by pengwangucla** [comment]
+1  how to recover the mesh after having these point cloud ?  Or the demo output is just a group of enlarged point clouds 

Or did you directly learn a nerf model from the point cloud for visualizing these results. If that is the case, wonder when the code could be released ?

**Comment by Dandelionym** [comment]
@chaoyuaw @Celebio  Hope the answer can be replied to soon. :-)

**Comment by gkioxari** [comment]
Hi all! The output of MCC is a 3D point cloud. Namely it's a set of colored 3D points: { $(x,y,z), (r,g,b)$ }. The visualizations we provide in the project page and the paper are Blender renderings of those colored 3D point clouds. There is no mesh extraction stage nor did we learn a NeRF model! 

We also provide plotly visualizations in embedded in html (click on the 3D button in the [project page](https://mcc3d.github.io/)). Alternatively, you can use PyTorch3D to render 3D point clouds to get 2D images or any other render you prefer!

**Comment by Dandelionym** [comment]
Thank you @gkioxari, you mean the results in your project page are from Blender using the output of MCC, which is the 3d points and colors.

I will try and if possible, some question may seek for your help.  >:-)

**Comment by gkioxari** [comment]
I realize that you might not be familiar with how to visualize 3D data. For completeness here is an explanation. The output of MCC is a 3D colored point cloud. To visualize any such 3D point cloud, one must use a renderer. In this particular paper, we use Blender to visualize the MCC outputs. In our webpage, we also visualize the results with a plotly which is another visualization scheme by rendering and which is interactive (click the 3D button).

**Comment by Dandelionym** [comment]
Thank you, professor @gkioxari, I've tried that and successfully done it. Thank you again.
