### ISSUE TITLE
Type of gpu?

### ISSUE THREAD

**Issue by YTEP-ZHI** [facebookresearch/MCC#13]
| We train with Adam [29] for 150k iterations with an effective batch size of 512 using 32 GPUs. Training takes∼2.5 days.
Here you mean V100 or A100 exactly? How about the memory size of these gpus you are using? 
Please let me know the computation cost of training such model. Thanks.

**Comment by chaoyuaw** [comment]
Hi @YTEP-ZHI, Thanks for the questions! We were using V100 GPUs. The training takes about 31GB out of the 32GB GPUs.

**Comment by YTEP-ZHI** [comment]
Thanks !

**Comment by SunghwanHong** [comment]
Hi @chaoyuaw, does this mean that you trained for around 15 epochs? How many epochs did you train for? When did you early stop?  Thanks!!
