### ISSUE TITLE
Get *.obj file of images generated by DALLE-2

### ISSUE THREAD

**Issue by Dandelionym** [facebookresearch/MCC#5]
> MCC works on images generated from [DALL·E 2](https://openai.com/dall-e-2/). Since the generated images do not include depth, we use [an off-the-shelf depth prediction model](https://github.com/isl-org/DPT) to estimate depth for these images before feeding to MCC.

Hi, may I ask, how to get the *.obj file corresponding to the image generated by DALLE-2?

I've tried:
* Only *.png depth image, segmentation image and *.pfm image can be obtained by the **DPT** repo you mentioned.

**Question: Could you please add another demo to help solve this problem?**

Thanks a lot. :-)

**Comment by chaoyuaw** [comment]
Hi @Dandelionym, 

Thanks for trying out! Yes, let me provide an outline first:
1. Create a camera, e.g., PyTorch3D's FoVPerspectiveCameras
2. Unproject depth into XYZ coordinates using, e.g. https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/implicitron/tools/point_cloud_utils.py#L23 or https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/cameras.py#L1385
This will give you the xyz points!

Please let me know if you have any questions!

**Comment by zhangfuyang** [comment]
Hi. I have one related question.

If I understand correctly, DPT model can only predict relative (normalized) depth from rgb image. Do you project this relative depth to get xyz points? Will this be a problem for the Pointcloud encoder part? Thank you!

**Comment by chaoyuaw** [comment]
Hi @zhangfuyang , 

As shown in demo.py, we normalize the input xyz points to be zero-mean and unit-variance, so the scale won't be an issue.
